file : 'sample.gnucash'

essentials:
    accounts: 
        - name: Rent
          budget: 1000
        - name: Utilities
          budget: 100
        - name: Groceries
          budget: 400
    budget: 1500
savings:
    accounts: 
        - name: Savings
          budget: 400
    budget: 400
personal:
    #   personal is implied every other accounts
    budget: 1000
income:
    paycheck: 4000